
[bell]
animation = "Ease"
color = "#ffffff"
duration = 150

# Colors (Konsole's Dark Pastels)

# Default colors
[colors.primary]
background = '#2C2C2C'
foreground = '#DCDCCC'

# Normal colors
[colors.normal]
black   = '#3F3F3F'
red     = '#705050'
green   = '#60B48A'
yellow  = '#DFAF8F'
blue    = '#9AB8D7'
magenta = '#DC8CC3'
cyan    = '#8CD0D3'
white   = '#DCDCCC'

# Bright colors
[colors.bright]
black   = '#709080'
red     = '#DCA3A3'
green   = '#72D5A3'
yellow  = '#F0DFAF'
blue    = '#94BFF3'
magenta = '#EC93D3'
cyan    = '#93E0E3'
white   = '#FFFFFF'

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Consolas"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"

[window]
decorations = "full"
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[terminal]

[general]
live_config_reload = true
