# dilla.glaze.files (https://github.com/dillacorn/win-glaze-dots)
# This config is my personalized config I use specifically for my gaming computer.
general:
  startup_commands: ["shell-exec yasb"]
  shutdown_commands: ["shell-exec taskkill /IM yasb.exe /F"]
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: "monitor_focus"
  hide_method: "cloak"
  show_all_in_taskbar: true

gaps:
  scale_with_dpi: true
  inner_gap: "2px"
  outer_gap:
    top: "38px"
    right: "8px"
    bottom: "8px"
    left: "8px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#b5bd68"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "square"
    transparency:
      enabled: false
      opacity: "95%"
  other_windows:
    border:
      enabled: false
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "square"
    transparency:
      enabled: false
      opacity: "95%"

window_behavior:
  initial_state: "tiling"
  state_defaults:
    floating:
      centered: false
      shown_on_top: true
    fullscreen:
      maximized: true
      shown_on_top: true

workspaces:
  - name: "1"
    display_name: "1: Flame"
    keep_alive: true
  - name: "2"
    display_name: "2: Brows"
  - name: "3"
    display_name: "3: Voip"
  - name: "4"
    display_name: "4: Game"
  - name: "5"
    display_name: "5: Music"
  - name: "6"
    display_name: "6: Chat"
  - name: "7"
    display_name: "7: Dev"
  - name: "8"
    display_name: "8: Work"
  - name: "9"
    display_name: "9: Edit"
  - name: "10"
    display_name: "10: Rec"

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { regex: "^(acad|acadlt)(\\.exe)?$" }

  - commands: ["move --workspace 1"]
    match:
      - window_process: { regex: "Marvel-Win64-Shipping|r5apex|r5apex_dx12|Discovery|cs2|RustClient|quakelive_steam|QuakeChampions|straftat|VALORANT-Win64-Shipping|ULTRAKILL|TotallyAccurateBattlegrounds|BattleBit|helldivers2|Schedule I" }

  - commands: ["move --workspace 2"]
    match:
      - window_process: { regex: "librewolf|firefox|chrome|brave" }

  - commands: ["move --workspace 3"]
    match:
      - window_process: { regex: "Discord|Vesktop|Dorion" }

  - commands: ["move --workspace 4"]
    match:
      - window_process: { regex: "steamwebhelper|EpicGamesLauncher|itch" }

  - commands: ["move --workspace 5"]
    match:
      - window_process: { regex: "Spotify" }

  - commands: ["move --workspace 5"]
    match:
      - window_process: { regex: "Feishin" }

  - commands: ["move --workspace 6"]
    match:
      - window_process: { regex: "Telegram" }

  - commands: ["move --workspace 8"]
    match:
      - window_process: { regex: "ms-teams" }

  - commands: ["move --workspace 9"]
    match:
      - window_process: { regex: "shotcut" }

  - commands: ["move --workspace 9"]
    match:
      - window_process: { regex: "krita" }

  - commands: ["move --workspace 10"]
    match:
      - window_process: { regex: "obs64" }

  - commands: ["ignore"]
    match:
      - window_process: { equals: "windhawk" }
      - window_process: { equals: "zebar" }
      - window_process: { equals: "yasb" }
      - window_process: { equals: "Flow.Launcher" }
      - window_process: { equals: "AltSnap" }
      - window_process: { equals: "flameshot" }
      - window_process: { equals: "LiveCaptions" }
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
      - window_process: { equals: "Mullvad VPN" }
      - window_process: { equals: "ui32" }
      - window_process: { equals: "wallpaper32" }
      - window_process: { equals: "wallpaper64" }
      - window_process: { equals: "TextInputHost" }
      - window_process: { equals: "Windows Input Experience" }
      - window_process: { equals: "acad" }
        window_class: { regex: "^(#32770|Afx:.*|Autodesk.*Dialog|Adsk.*|WindowsForms10\\.Window\\.8\\.app\\..*|ComboLBox|tooltips_class32)$" }
      - window_process: { regex: "^(ADPClientService|AdskAccessUIHost|AdskAccessCore|AdSSO|AdskIdentityManager)$" }
      - window_process: { equals: "LTSVC" }
      - window_process: { equals: "LTSvcMon" }
      - window_process: { equals: "LTTray" }

  - commands: ["set-floating"]
    match:
      - window_process: { equals: "Taskmgr" }
      - window_process: { equals: "speedcrunch" }
      - window_process: { equals: "winspy" }
      - window_process: { equals: "localsend_app" }
      - window_process: { equals: "RustDesk" }
      - window_process: { equals: "ApplicationFrameHost" }
      - window_title: { regex: "^Insert Pages$" }

  - commands: ["set-floating --centered"]
    match:
      - window_title: { regex: "Volume Mixer" }
      - window_process: { equals: "EarTrumpet" }
      - window_title: { regex: "(Find|Replace)" }

binding_modes:
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["l", "right"]
      - commands: ["resize --width +2%"]
        bindings: ["h", "left"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]

keybindings:
  - commands: ["shell-exec flameshot gui"]
    bindings: ["win+shift+f"]

  - commands:
      - shell-exec --hide-window powershell -NoProfile -Command "if (Get-Process yasb -ErrorAction SilentlyContinue) { Stop-Process -Name yasb -Force } else { Start-Process yasb }"
    bindings: ["alt+ctrl+b"]

  - commands: ['shell-exec C:\Program Files (x86)\SpeedCrunch\speedcrunch.exe']
    bindings: ["alt+shift+c"]

  - commands: ["shell-exec explorer.exe http:"]
    bindings: ["win+b"]

  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down"]

  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  - commands: ["resize --width -2%"]
    bindings: ["alt+y", "alt+ctrl+left"]
  - commands: ["resize --width +2%"]
    bindings: ["alt+o", "alt+ctrl+right"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+i", "alt+ctrl+up"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+u", "alt+ctrl+down"]

  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+shift+r"]

  - commands: ["toggle-floating --centered"]
    bindings: ["alt+f"]

  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

  - commands:
      - "toggle-fullscreen"
      - "shell-exec --hide-window powershell -NoProfile -WindowStyle Hidden -Command \"Start-Sleep -Milliseconds 70; Start-Process -WindowStyle Hidden glazewm -ArgumentList 'command wm-redraw'\""
    bindings: ["alt+ctrl+f"]

  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  - commands: ["close"]
    bindings: ["alt+shift+q"]

  - commands: ["wm-exit"]
    bindings: ["alt+ctrl+shift+k"]

  - commands: ["wm-reload-config"]
    bindings: ["alt+ctrl+shift+q"]

  - commands: ["wm-redraw"]
    bindings: ["alt+ctrl+shift+w"]

  # Launch a normal Windows Terminal window.
  - commands: ["shell-exec wt.exe -w new"]
    bindings: ["alt+shift+enter"]

  # Launch Yazi in a dedicated Windows Terminal window.
  - commands: ["shell-exec wt.exe -w new new-tab --title \"Yazi\" --suppressApplicationTitle powershell.exe -NoProfile -NoLogo -NoExit -Command yazi"]
    bindings: ["alt+shift+e"]

  - commands: ["focus --next-workspace"]
    bindings: ["alt+]"]
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+["]

  - commands: ["focus --recent-workspace"]
    bindings: ["alt+ctrl+c"]

  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]
  - commands: ["focus --workspace 10"]
    bindings: ["alt+0"]

  - commands: ["move-workspace --direction left"]
    bindings: ["alt+ctrl+shift+left"]
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+ctrl+shift+right"]
  - commands: ["move-workspace --direction up"]
    bindings: ["alt+ctrl+shift+up"]
  - commands: ["move-workspace --direction down"]
    bindings: ["alt+ctrl+shift+down"]

  - commands: ["move --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9"]
    bindings: ["alt+shift+9"]
  - commands: ["move --workspace 10"]
    bindings: ["alt+shift+0"]

  # Launch the user's scripts menu in Windows Terminal.
  - commands: ["shell-exec wt.exe -w new new-tab --title \"Scripts\" --suppressApplicationTitle -d \"%USERPROFILE%\\scripts\" cmd.exe /k menu.bat"]
    bindings: ["alt+shift+m"]
