watch_stylesheet: true
watch_config: true
debug: false
show_systray: false

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"

    alignment:
      position: "top"
      align: "center"

    blur_effect:
      enabled: false
      dark_mode: false
      round_corners: false
      border_color: None

    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true

    dimensions:
      width: "100%"
      height: 28

    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0

    animation:
      enabled: false
      duration: 0

    widgets:
      left:
        [
          "launcher",
          "glazewm_workspaces",
          "workspace_move_group",
          "taskbar",
          "glazewm_binding_mode",
        ]
      center: ["active_window"]
      right:
        [
          "cpu",
          "memory",
          "brightness",
          "battery",
          "microphone",
          "volume",
          "clock",
          "wifi",
          "bluetooth",
          "systray",
          "clipboard_history",
          "notifications",
          "dnd",
          "power_menu",
        ]

widgets:
  launcher:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      class_name: "awtarchy-launcher"
      image_icon_size: 14
      tooltip: true
      app_list:
        - icon: ""
          launch: "wgdot flow-open"
          name: "Flow Launcher"

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      populated_label: "{name}"
      empty_label: "{name}"
      active_populated_label: "{name}"
      active_empty_label: "{name}"
      focused_populated_label: "{name}"
      focused_empty_label: "{name}"
      hide_if_offline: false
      monitor_exclusive: true
      enable_scroll_switching: true
      reverse_scroll_direction: false
      app_icons:
        enabled_populated: false
        enabled_active: false
        enabled_focused: false

  workspace_move:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      class_name: "workspace-move-buttons"
      tooltip: true
      app_list:
        - icon: "←"
          launch: "glazewm.exe command move-workspace --direction left"
          name: "Move workspace left"
        - icon: "↑"
          launch: "glazewm.exe command move-workspace --direction up"
          name: "Move workspace up"
        - icon: "↓"
          launch: "glazewm.exe command move-workspace --direction down"
          name: "Move workspace down"
        - icon: "→"
          launch: "glazewm.exe command move-workspace --direction right"
          name: "Move workspace right"

  workspace_move_group:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "workspace-move-grouper"
      widgets: ["workspace_move"]
      hide_empty: false
      collapse_options:
        enabled: true
        exclude_widgets: []
        expanded_label: "󰍽"
        collapsed_label: "󰍽"
        label_position: "left"

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: true
      hide_empty: true
      callbacks:
        on_left: "toggle_window"
        on_middle: "close_app"
        on_right: "toggle_window"
      animation:
        enabled: false
        duration: 0
      preview:
        enabled: false
        width: 240
        delay: 400
        padding: 8
        margin: 8
      grouping:
        enabled: false
        show_count: true
      title_label:
        enabled: false
        show: "always"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []

  glazewm_binding_mode:
    type: "glazewm.binding_mode.GlazewmBindingModeWidget"
    options:
      label: "{binding_mode}"
      label_alt: "{binding_mode}"
      hide_if_no_active: true
      label_if_no_active: ""
      default_icon: ""
      icons:
        none: ""
        noalt: ""
        vm: ""
      binding_modes_to_cycle_through: ["none", "noalt", "vm"]
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "disable_binding_mode"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "{win[title]}"
      label_no_window: ""
      label_icon: false
      label_icon_size: 14
      max_length: 64
      max_length_ellipsis: "..."
      monitor_exclusive: true

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "{info[percent][total]}% "
      label_alt: "{info[freq][current]} MHz"
      update_interval: 2000
      hide_decimal: true
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      menu:
        enabled: true
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"
        show_graph: true
        show_graph_grid: false
        graph_history_size: 60

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "{virtual_mem_percent}% "
      label_alt: "{virtual_mem_used} / {virtual_mem_total}"
      update_interval: 5000
      hide_decimal: true
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      menu:
        enabled: true
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"
        show_graph: true
        show_graph_grid: false
        graph_history_size: 60

  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "Brightness {percent}%"
      tooltip: true
      scroll_step: 5
      invert_wheel: false
      ddc_poll_interval: 60
      brightness_menu:
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_brightness_menu"
        on_middle: "do_nothing"
        on_right: "toggle_brightness_menu"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% {time_remaining}"
      update_interval: 5000
      hide_unsupported: true
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: false
        blink_interval: 500
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {level}"
      mute_text: "mute"
      tooltip: true
      scroll_step: 2
      icons:
        normal: ""
        muted: ""
      mic_menu:
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_mic_menu"
        on_middle: "toggle_label"
        on_right: "toggle_mute"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}"
      mute_text: "mute"
      tooltip: true
      scroll_step: 2
      slider_beep: false
      icons:
        muted: ""
        "10": ""
        "30": ""
        "60": ""
        "100": ""
      audio_menu:
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"
        show_apps: true
        show_app_labels: false
        show_app_icons: true
        show_apps_expanded: false
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "toggle_volume_menu"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span></span> {%H:%M}"
      label_alt: "<span></span> {%a %m/%d}"
      tooltip: true
      update_interval: 1000
      timezones: []
      calendar:
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"
        show_holidays: false
        show_week_numbers: false
        show_years: true
        extended: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "toggle_calendar"
        on_right: "toggle_label"

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      get_exact_wifi_strength: false
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_menu"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span> {ip_addr}"
      ethernet_icon: ""
      wifi_icons:
        [
          "󰤮",
          "󰤟",
          "󰤢",
          "󰤥",
          "󰤨",
        ]
      menu_config:
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"

  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{device_name}"
      tooltip: true
      icons:
        bluetooth_on: "󰂯"
        bluetooth_off: "󰂲"
        bluetooth_connected: "󰂱"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_menu"
      menu_config:
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      icon_size: 16
      tooltip: true
      show_unpinned: true
      show_unpinned_button: false
      show_in_popup: false
      show_battery: false
      show_volume: false
      show_network: false
      use_hook: false
      hide_icons: []

  clipboard_history:
    type: "yasb.quick_launch.QuickLaunchWidget"
    options:
      label: "<span></span>"
      search_placeholder: "Search clipboard history..."
      remember_last_query: false
      max_results: 30
      show_icons: true
      icon_size: 28
      home_page: false
      compact_mode: false
      compact_text: true
      providers:
        apps:
          enabled: false
        snippets:
          enabled: false
        color:
          enabled: false
        clipboard_history:
          enabled: true
          prefix: "*"
          priority: 0
          max_items: 30
          show_preview: true
      popup:
        width: 720
        height: 480
        blur: false
        round_corners: false
        border_color: None
        dark_mode: true
      callbacks:
        on_left: "toggle_quick_launch"
        on_middle: "do_nothing"
        on_right: "toggle_quick_launch"

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {count}"
      tooltip: true
      hide_empty: false
      icons:
        new: "󰂞"
        default: "󰂚"
      callbacks:
        on_left: "toggle_notification"
        on_middle: "toggle_label"
        on_right: "do_nothing"

  dnd:
    type: "yasb.dnd.DndWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {status}"
      class_name: "awtarchy-dnd"
      tooltip: true
      default_active_mode: "priority"
      icons:
        disabled: ""
        priority: ""
        alarms: ""
      callbacks:
        on_left: "toggle_status"
        on_middle: "toggle_label"
        on_right: "toggle_status"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span></span>"
      uptime: false
      show_user: false
      animation_duration: 0
      menu_style: "popup"
      callbacks:
        on_left: "toggle_power_menu"
        on_middle: "do_nothing"
        on_right: "toggle_power_menu"
      popup:
        blur: false
        round_corners: false
        border_color: None
        alignment: "right"
        direction: "down"
      buttons:
        lock: ["", "Lock"]
        signout: ["󰍃", "Sign out"]
        sleep: ["󰤄", "Sleep"]
        restart: ["", "Restart"]
        shutdown: ["", "Shut Down"]
        cancel: ["", "Cancel"]
