# github.com/dillacorn/win-glaze-dots
# %APPDATA%\yazi\config\yazi.toml

# Keep Yazi minimally opinionated on Windows:
# - text/code uses Micro
# - everything else uses normal Windows file associations

[mgr]
linemode = "size_and_mtime"
mouse_events = ["click", "scroll", "drag", "move"]

[opener]
edit = [
    { run = 'wt.exe -w new new-tab --title "Micro" --suppressApplicationTitle --startingDirectory %d1 micro.exe %s', orphan = true, desc = "Micro", for = "windows" },
]

open = [
    { run = 'cmd.exe /d /c start "" /D %d1 %s1', orphan = true, desc = "Open", for = "windows" },
]

play = [
    { run = 'cmd.exe /d /c start "" /D %d1 %s1', orphan = true, desc = "Open", for = "windows" },
]
